### ISSUE TITLE
Add other emails/users as recipient

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-ContactUs#1]
Hi,

Thank for this very useful module.

`the email is the site admin one`: how can I add other (several) emails (or user) as recipient?

The current behavior would be problematic if the site creator is not working anymore on the project. There is no simple way (to my knowledge) to change a site "owner".

Also, it would be very nice to have a little form to indicate if you want to reach scientific editors or engineer with different emails/users behind.

**Comment by Daniel-KM** [comment]
Yes, it's not a complex thing to add in the form, but a work to be done...

**Comment by Daniel-KM** [comment]
Fixed.
