### ISSUE TITLE
Issue with antispam using PHP 8.2

### ISSUE THREAD

**Issue by saponidas** [Daniel-KM/Omeka-S-module-ContactUs#10]
Hi, there is an error when submitting the contact form if the antispam is enabled (PHP 8.2)

---------
ENVIROMENT:
Linux Ubuntu 22
Apache2
Mysql 8
PHP 8.2

---------

Using php 7.4 it works fine. I have not tested php 8.0 and 8.1

`
Error
Unknown named parameter $checkAnswer
`

Details:

`Error: Unknown named parameter $checkAnswer in /var/www/yoursite/public_html/vendor/laminas/laminas-validator/src/Callback.php:139`
Stack trace:
`#0 /var/www/yoursite/public_html/vendor/laminas/laminas-validator/src/ValidatorChain.php(242): Laminas\Validator\Callback->isValid()
#1 /var/www/yoursite/public_html/vendor/laminas/laminas-inputfilter/src/Input.php(410): Laminas\Validator\ValidatorChain->isValid()
#2 /var/www/yoursite/public_html/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(273): Laminas\InputFilter\Input->isValid()
#3 /var/www/yoursite/public_html/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(226): Laminas\InputFilter\BaseInputFilter->validateInputs()
#4 /var/www/yoursite/public_html/vendor/laminas/laminas-form/src/Form.php(481): Laminas\InputFilter\BaseInputFilter->isValid()
#5 /var/www/yoursite/public_html/modules/ContactUs/src/View/Helper/ContactUs.php(192): Laminas\Form\Form->isValid()
#6 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): ContactUs\View\Helper\ContactUs->__invoke()
#7 /var/www/yoursite/public_html/modules/ContactUs/view/common/block-layout/contact-us.phtml(7): Laminas\View\Renderer\PhpRenderer->__call()
#8 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('...')
#9 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/Helper/Partial.php(63): Laminas\View\Renderer\PhpRenderer->render()
#10 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): Laminas\View\Helper\Partial->__invoke()
#11 /var/www/yoursite/public_html/modules/ContactUs/src/Site/BlockLayout/ContactUs.php(131): Laminas\View\Renderer\PhpRenderer->__call()
#12 /var/www/yoursite/public_html/application/src/View/Helper/BlockLayout.php(124): ContactUs\Site\BlockLayout\ContactUs->render()
#13 /var/www/yoursite/public_html/application/view/omeka/site/page/content.phtml(9): Omeka\View\Helper\BlockLayout->render()
#14 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('...')
#15 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render()
#16 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render()
#17 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren()
#18 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render()
#19 /var/www/yoursite/public_html/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren()
#20 /var/www/yoursite/public_html/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render()
#21 /var/www/yoursite/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#22 /var/www/yoursite/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#23 /var/www/yoursite/public_html/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent()
#24 /var/www/yoursite/public_html/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest()
#25 /var/www/yoursite/public_html/index.php(21): Laminas\Mvc\Application->run()
#26 {main}`

Thanks in advance,

**Comment by jajm** [comment]
Same error with PHP 8.0 (so probably with PHP 8.1 too)
