### ISSUE TITLE
Accent in body not supported

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-ContactUs#2]
There is an encoding issue with emails sent by the contact form. Accented letters in body (in subject ) are not supported. 

Maybe, emails body are not encoded in UTF8 ?

**Comment by Daniel-KM** [comment]
I can't reproduce your issue, it works on my server. 

The module uses the Zend mailer and the params in the Omeka config. So the issue is probably in the server config.

**Comment by pprw** [comment]
I can confirm it is mail client related. Thundebird for me seems to not detect the email as unicode and does not show accents. It works when you force unicode. Other mailers don't have this issue.
