### ISSUE TITLE
not able to add block to page

### ISSUE THREAD

**Issue by kfherbert** [Daniel-KM/Omeka-S-module-ContactUs#3]
I have installed the module to my omeka-s install (version 1.4.0) but when I try to add the block to a page the link on the side bar is titled "unknown [contact-us]" when I add it, I get "This layout is invalid."

**Comment by Daniel-KM** [comment]
You may have to update the module.

**Comment by zachwhalen** [comment]
I have this error as well in Omeka S version 1.4.0, Contact Us module version 3.0.1.

**Comment by Daniel-KM** [comment]
There is probably a compatibility issue somewhere. Can you show me a screenshot of the page edit ?

**Comment by zachwhalen** [comment]
Here's what it looks like when I try to add the block in the page editor:

<img width="682" alt="Screen Shot 2019-07-24 at 9 31 12 AM" src="https://user-images.githubusercontent.com/291418/61797658-d3971f00-adf5-11e9-945e-2ae3350c7ab2.png">

**Comment by Daniel-KM** [comment]
It's strange, it works on a clean install and on other install I have. Are you on Windows ?
I just published version 3.0.2 too, that fix another point.

**Comment by zachwhalen** [comment]
I upgraded to version 3.0.2 and it works normally now.

**Comment by Daniel-KM** [comment]
I find the issue : the module folder should be `ContactUs`, no `Contactus`.
