### ISSUE TITLE
Add option to prevent showing the contact form on item, item set, media show pages

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-ContactUs#4]
Readme:
> The form is displayed automatically on item set, item or media show pages. The settings can be set for each site.

It seems to be no the case. I have no option, in the site settings, to disable the contact form for item show page for example. I have option to configure the form for each site though.

**Comment by Daniel-KM** [comment]
I just updated the readme for that: I removed such options in all my modules, so you can now use a better display with module [Blocks Disposition](https://github.com/Daniel-KM/Omeka-S-module-BlocksDisposition).
