### ISSUE TITLE
bug affichage selection message depuis admin

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-ContactUs#7]
Il semble qu'il y ait un bug d'affichage quand on sélectionne un ou plusieurs messages depuis l'interface admin.

![image](https://user-images.githubusercontent.com/5262986/212713216-df3d1f9c-7540-4415-a5b9-f39e94fbc453.png)

**Comment by Daniel-KM** [comment]
Pas reproductible dans la version courante.
